import type { Action } from "../components/ActionDetailModal";

export const ALL_ACTIONS: Action[] = [
  {
    id: 1,
    title: "Fahrrad-Tracking",
    titleEn: "Bike Tracking",
    description: "Tracke deine Fahrradfahrt zur Hochschule",
    descriptionEn: "Track your bike ride to university",
    icon: "🚴",
    coinsPer5Min: 5,
    category: "cycling",
    color: "from-blue-500 to-blue-600",
    coins: "5 Coins / 5 Min",
    details: "Fahre mit dem Fahrrad zur Hochschule und sammle dabei Eco Coins. Je länger deine Fahrt, desto mehr Punkte erhältst du!",
    detailsEn: "Bike to university and earn Eco Coins. The longer your ride, the more points you get!",
    instructions: [
      "Starte das Tracking, bevor du losfährst",
      "Fahre zur Hochschule München",
      "Beende das Tracking bei Ankunft",
      "Erhalte deine Coins automatisch",
    ],
    instructionsEn: [
      "Start tracking before you begin",
      "Bike to Munich University",
      "Stop tracking when you arrive",
      "Receive your coins automatically",
    ],
  },
  {
    id: 2,
    title: "Recycling Scanner",
    titleEn: "Recycling Scanner",
    description: "Scanne deine Pfandflaschen",
    descriptionEn: "Scan your deposit bottles",
    icon: "♻️",
    coinsPer5Min: 3,
    category: "recycling",
    color: "from-green-500 to-green-600",
    coins: "3 Coins / Flasche",
    details: "Scanne Pfandflaschen und erhalte Coins für dein Recycling-Engagement!",
    detailsEn: "Scan deposit bottles and receive coins for your recycling effort!",
    instructions: [
      "Öffne den Scanner",
      "Scanne den Barcode der Pfandflasche",
      "Wirf die Flasche in den richtigen Behälter",
      "Erhalte deine Coins",
    ],
    instructionsEn: [
      "Open the scanner",
      "Scan the bottle barcode",
      "Put the bottle in the correct bin",
      "Receive your coins",
    ],
  },
  {
    id: 3,
    title: "Mehrweg-Becher",
    titleEn: "Reusable Cup",
    description: "Nutze deinen Mehrwegbecher",
    descriptionEn: "Use your reusable cup",
    icon: "🥤",
    coinsPer5Min: 4,
    category: "reusable-cup",
    color: "from-amber-500 to-amber-600",
    coins: "4 Coins / Nutzung",
    details: "Verwende deinen Mehrwegbecher in der Mensa oder Cafeteria und spare Einwegmüll!",
    detailsEn: "Use your reusable cup in the cafeteria and save disposable waste!",
    instructions: [
      "Nimm deinen Mehrwegbecher mit",
      "Kaufe ein Getränk an der Theke",
      "Lasse den Becher befüllen",
      "Erhalte deine Coins",
    ],
    instructionsEn: [
      "Bring your reusable cup",
      "Buy a drink at the counter",
      "Have your cup filled",
      "Receive your coins",
    ],
  },
  {
    id: 6,
    title: "Büchertausch",
    titleEn: "Book Exchange",
    description: "Tausche oder gebe Bücher in der Bibliothek ab",
    descriptionEn: "Exchange or donate books at the library",
    icon: "📚",
    coinsPer5Min: 50,
    category: "book-exchange",
    color: "from-indigo-500 to-indigo-600",
    coins: "50 Coins / Buch",
    details: "Tausche oder gebe Bücher an den Bücherregalen in der Bibliothek ab und fördere nachhaltiges Teilen!",
    detailsEn: "Exchange or donate books at the library book shelves and promote sustainable sharing!",
    instructions: [
      "Gehe zu den Bücherregalen in der Bibliothek",
      "Tausche ein Buch oder gebe eines ab",
      "Dokumentiere den Tausch",
      "Erhalte 50 Coins pro getauschtem/abgegebenem Buch",
    ],
    instructionsEn: [
      "Go to the book shelves in the library",
      "Exchange or donate a book",
      "Document the exchange",
      "Receive 50 coins per exchanged/donated book",
    ],
  },
  {
    id: 7,
    title: "Event-Teilnahme",
    titleEn: "Event Participation",
    description: "Nimm an Nachhaltigkeits-Events teil",
    descriptionEn: "Participate in sustainability events",
    icon: "🎯",
    coinsPer5Min: 30,
    category: "event-participation",
    color: "from-purple-500 to-purple-600",
    coins: "30 Coins / Event",
    details: "Besuche Workshops, Vorträge und andere Nachhaltigkeits-Events an der Hochschule!",
    detailsEn: "Attend workshops, lectures and other sustainability events at the university!",
    instructions: [
      "Finde Events im News-Feed",
      "Melde dich für ein Event an",
      "Nimm am Event teil",
      "Erhalte deine Coins nach der Teilnahme",
    ],
    instructionsEn: [
      "Find events in the news feed",
      "Register for an event",
      "Participate in the event",
      "Receive your coins after participation",
    ],
  },
];
